name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web-analysis-dashboard/requirements_production.txt

      - name: Run smoke tests
        env:
          DATABASE_URL: sqlite:///:memory:
          SECRET_KEY: ci-secret
        run: |
          pytest -q web-analysis-dashboard/test_api_smoke.py

